# Generated by Django 4.1.1 on 2022-09-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buyinguser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nUsuario', models.CharField(max_length=20)),
                ('nCompleto', models.CharField(max_length=80)),
                ('emailUsuario', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='salecellphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellphoneModel', models.CharField(max_length=60)),
                ('cellphoneBrand', models.CharField(max_length=20)),
                ('cellphoneQty', models.IntegerField()),
                ('cellphonePrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='salecomputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computerModel', models.CharField(max_length=60)),
                ('computerBrand', models.CharField(max_length=20)),
                ('computerQty', models.IntegerField()),
                ('computerPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='saleprinter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printerModel', models.CharField(max_length=60)),
                ('printerBrand', models.CharField(max_length=20)),
                ('printerQty', models.IntegerField()),
                ('printerPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='salerouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routerModel', models.CharField(max_length=60)),
                ('routerBrand', models.CharField(max_length=20)),
                ('routerQty', models.IntegerField()),
                ('routerPrice', models.IntegerField()),
            ],
        ),
    ]
